### ISSUE TITLE
下载安装后，总是提示错误

### ISSUE THREAD

**Issue by huiguyy** [gstory0404/chatgpt_app#1]
总出现：Future<String> 错误提示

**Comment by gstory0404** [comment]
具体信息 是app.中提示吗

**Comment by huiguyy** [comment]
![WechatIMG277](https://user-images.githubusercontent.com/89367838/218711847-4d472e1a-7e61-462a-aaa6-08e1f44c4475.jpeg)

**Comment by gstory0404** [comment]
@huiguyy 重新下载
